AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance, EIP and associate with instance
   
Parameters:

  ImageId:
    Type: String
    Description: 'Linux 2 AMI for Ireland eu-west1 Region'
    Default: 'ami-0d5eff06f840b45e9'
  InstanceType:
    Type: String
    Description: Choosing  t2 micro because it is free
    Default: t2.micro
  KeyName:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: 123@test

Resources:
  PracInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
  
  #Allocate an Elastic IP in your Account
  PracElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref PracInstance 

Outputs:
  DemoInstanceId:
    Description: Instance Id 
    Value: !Ref PracInstance